language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t estimateflake/docker-react -f Dockerfile.dev .
#script:
#  - docker run estimateflake/docker-react npm run test -- --coverage
script:
  - docker run -e CI=true estimateflake/docker-react npm run test
